# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from calculator.v1 import calculator_api_pb2 as calculator_dot_v1_dot_calculator__api__pb2
from calculator.v1 import calculator_pb2 as calculator_dot_v1_dot_calculator__pb2


class CalculatorAPIStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetExchangeRates = channel.unary_unary(
                '/calculator.v1.CalculatorAPI/GetExchangeRates',
                request_serializer=calculator_dot_v1_dot_calculator__api__pb2.GetExchangeRatesRequest.SerializeToString,
                response_deserializer=calculator_dot_v1_dot_calculator__api__pb2.GetExchangeRatesResponse.FromString,
                )
        self.GetSnakeData = channel.unary_stream(
                '/calculator.v1.CalculatorAPI/GetSnakeData',
                request_serializer=calculator_dot_v1_dot_calculator__api__pb2.GetSnakeDataRequest.SerializeToString,
                response_deserializer=calculator_dot_v1_dot_calculator__pb2.Datum.FromString,
                )
        self.GetSnakeDataUnary = channel.unary_unary(
                '/calculator.v1.CalculatorAPI/GetSnakeDataUnary',
                request_serializer=calculator_dot_v1_dot_calculator__api__pb2.GetSnakeDataRequest.SerializeToString,
                response_deserializer=calculator_dot_v1_dot_calculator__api__pb2.GetSnakeDataUnaryResponse.FromString,
                )


class CalculatorAPIServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetExchangeRates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSnakeData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSnakeDataUnary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculatorAPIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetExchangeRates': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExchangeRates,
                    request_deserializer=calculator_dot_v1_dot_calculator__api__pb2.GetExchangeRatesRequest.FromString,
                    response_serializer=calculator_dot_v1_dot_calculator__api__pb2.GetExchangeRatesResponse.SerializeToString,
            ),
            'GetSnakeData': grpc.unary_stream_rpc_method_handler(
                    servicer.GetSnakeData,
                    request_deserializer=calculator_dot_v1_dot_calculator__api__pb2.GetSnakeDataRequest.FromString,
                    response_serializer=calculator_dot_v1_dot_calculator__pb2.Datum.SerializeToString,
            ),
            'GetSnakeDataUnary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSnakeDataUnary,
                    request_deserializer=calculator_dot_v1_dot_calculator__api__pb2.GetSnakeDataRequest.FromString,
                    response_serializer=calculator_dot_v1_dot_calculator__api__pb2.GetSnakeDataUnaryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calculator.v1.CalculatorAPI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CalculatorAPI(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetExchangeRates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calculator.v1.CalculatorAPI/GetExchangeRates',
            calculator_dot_v1_dot_calculator__api__pb2.GetExchangeRatesRequest.SerializeToString,
            calculator_dot_v1_dot_calculator__api__pb2.GetExchangeRatesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSnakeData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/calculator.v1.CalculatorAPI/GetSnakeData',
            calculator_dot_v1_dot_calculator__api__pb2.GetSnakeDataRequest.SerializeToString,
            calculator_dot_v1_dot_calculator__pb2.Datum.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSnakeDataUnary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calculator.v1.CalculatorAPI/GetSnakeDataUnary',
            calculator_dot_v1_dot_calculator__api__pb2.GetSnakeDataRequest.SerializeToString,
            calculator_dot_v1_dot_calculator__api__pb2.GetSnakeDataUnaryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
