# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator/v1/calculator_api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from calculator.v1 import calculator_pb2 as calculator_dot_v1_dot_calculator__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='calculator/v1/calculator_api.proto',
  package='calculator.v1',
  syntax='proto3',
  serialized_options=b'Z\030calculator/v1;calculator',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\"calculator/v1/calculator_api.proto\x12\rcalculator.v1\x1a\x1e\x63\x61lculator/v1/calculator.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"[\n\x17GetExchangeRatesRequest\x12\x0c\n\x04\x66rom\x18\x01 \x01(\t\x12\n\n\x02to\x18\x02 \x01(\t\x12&\n\x02on\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x9a\x01\n\x18GetExchangeRatesResponse\x12\x0c\n\x04\x66rom\x18\x01 \x01(\t\x12\n\n\x02to\x18\x02 \x01(\t\x12&\n\x02on\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nexact_date\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04rate\x18\x05 \x01(\x01\"/\n\x13GetSnakeDataRequest\x12\x18\n\x10snake_expression\x18\x01 \x01(\t\"?\n\x19GetSnakeDataUnaryResponse\x12\"\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x14.calculator.v1.Datum2\xa9\x02\n\rCalculatorAPI\x12\x65\n\x10GetExchangeRates\x12&.calculator.v1.GetExchangeRatesRequest\x1a\'.calculator.v1.GetExchangeRatesResponse\"\x00\x12L\n\x0cGetSnakeData\x12\".calculator.v1.GetSnakeDataRequest\x1a\x14.calculator.v1.Datum\"\x00\x30\x01\x12\x63\n\x11GetSnakeDataUnary\x12\".calculator.v1.GetSnakeDataRequest\x1a(.calculator.v1.GetSnakeDataUnaryResponse\"\x00\x42\x1aZ\x18\x63\x61lculator/v1;calculatorb\x06proto3'
  ,
  dependencies=[calculator_dot_v1_dot_calculator__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_GETEXCHANGERATESREQUEST = _descriptor.Descriptor(
  name='GetExchangeRatesRequest',
  full_name='calculator.v1.GetExchangeRatesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='from', full_name='calculator.v1.GetExchangeRatesRequest.from', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='to', full_name='calculator.v1.GetExchangeRatesRequest.to', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='on', full_name='calculator.v1.GetExchangeRatesRequest.on', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=209,
)


_GETEXCHANGERATESRESPONSE = _descriptor.Descriptor(
  name='GetExchangeRatesResponse',
  full_name='calculator.v1.GetExchangeRatesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='from', full_name='calculator.v1.GetExchangeRatesResponse.from', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='to', full_name='calculator.v1.GetExchangeRatesResponse.to', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='on', full_name='calculator.v1.GetExchangeRatesResponse.on', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='exact_date', full_name='calculator.v1.GetExchangeRatesResponse.exact_date', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rate', full_name='calculator.v1.GetExchangeRatesResponse.rate', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=212,
  serialized_end=366,
)


_GETSNAKEDATAREQUEST = _descriptor.Descriptor(
  name='GetSnakeDataRequest',
  full_name='calculator.v1.GetSnakeDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='snake_expression', full_name='calculator.v1.GetSnakeDataRequest.snake_expression', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=368,
  serialized_end=415,
)


_GETSNAKEDATAUNARYRESPONSE = _descriptor.Descriptor(
  name='GetSnakeDataUnaryResponse',
  full_name='calculator.v1.GetSnakeDataUnaryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='calculator.v1.GetSnakeDataUnaryResponse.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=417,
  serialized_end=480,
)

_GETEXCHANGERATESREQUEST.fields_by_name['on'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_GETEXCHANGERATESRESPONSE.fields_by_name['on'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_GETEXCHANGERATESRESPONSE.fields_by_name['exact_date'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_GETSNAKEDATAUNARYRESPONSE.fields_by_name['data'].message_type = calculator_dot_v1_dot_calculator__pb2._DATUM
DESCRIPTOR.message_types_by_name['GetExchangeRatesRequest'] = _GETEXCHANGERATESREQUEST
DESCRIPTOR.message_types_by_name['GetExchangeRatesResponse'] = _GETEXCHANGERATESRESPONSE
DESCRIPTOR.message_types_by_name['GetSnakeDataRequest'] = _GETSNAKEDATAREQUEST
DESCRIPTOR.message_types_by_name['GetSnakeDataUnaryResponse'] = _GETSNAKEDATAUNARYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetExchangeRatesRequest = _reflection.GeneratedProtocolMessageType('GetExchangeRatesRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETEXCHANGERATESREQUEST,
  '__module__' : 'calculator.v1.calculator_api_pb2'
  # @@protoc_insertion_point(class_scope:calculator.v1.GetExchangeRatesRequest)
  })
_sym_db.RegisterMessage(GetExchangeRatesRequest)

GetExchangeRatesResponse = _reflection.GeneratedProtocolMessageType('GetExchangeRatesResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETEXCHANGERATESRESPONSE,
  '__module__' : 'calculator.v1.calculator_api_pb2'
  # @@protoc_insertion_point(class_scope:calculator.v1.GetExchangeRatesResponse)
  })
_sym_db.RegisterMessage(GetExchangeRatesResponse)

GetSnakeDataRequest = _reflection.GeneratedProtocolMessageType('GetSnakeDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETSNAKEDATAREQUEST,
  '__module__' : 'calculator.v1.calculator_api_pb2'
  # @@protoc_insertion_point(class_scope:calculator.v1.GetSnakeDataRequest)
  })
_sym_db.RegisterMessage(GetSnakeDataRequest)

GetSnakeDataUnaryResponse = _reflection.GeneratedProtocolMessageType('GetSnakeDataUnaryResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETSNAKEDATAUNARYRESPONSE,
  '__module__' : 'calculator.v1.calculator_api_pb2'
  # @@protoc_insertion_point(class_scope:calculator.v1.GetSnakeDataUnaryResponse)
  })
_sym_db.RegisterMessage(GetSnakeDataUnaryResponse)


DESCRIPTOR._options = None

_CALCULATORAPI = _descriptor.ServiceDescriptor(
  name='CalculatorAPI',
  full_name='calculator.v1.CalculatorAPI',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=483,
  serialized_end=780,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetExchangeRates',
    full_name='calculator.v1.CalculatorAPI.GetExchangeRates',
    index=0,
    containing_service=None,
    input_type=_GETEXCHANGERATESREQUEST,
    output_type=_GETEXCHANGERATESRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetSnakeData',
    full_name='calculator.v1.CalculatorAPI.GetSnakeData',
    index=1,
    containing_service=None,
    input_type=_GETSNAKEDATAREQUEST,
    output_type=calculator_dot_v1_dot_calculator__pb2._DATUM,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetSnakeDataUnary',
    full_name='calculator.v1.CalculatorAPI.GetSnakeDataUnary',
    index=2,
    containing_service=None,
    input_type=_GETSNAKEDATAREQUEST,
    output_type=_GETSNAKEDATAUNARYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALCULATORAPI)

DESCRIPTOR.services_by_name['CalculatorAPI'] = _CALCULATORAPI

# @@protoc_insertion_point(module_scope)
